### ISSUE TITLE
Ringworlds crash my video card and the game even w/ "Safe Ringworlds"

### ISSUE THREAD

**Issue by l29ah** [DaloLorn/Rising-Stars#66] opened 2018-10-16 19:58 UTC
Linux l29ah-x201 4.19.0-rc6+ #107 SMP PREEMPT Wed Oct 3 19:13:19 MSK 2018 x86_64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz GenuineIntel GNU/Linux

**Comment by l29ah** [comment] 2018-10-16 20:50
Removing the "atmoMask == 0" branch "fixes" it.

**Comment by DaloLorn** [comment] 2018-10-18 13:29
Interesting... I wonder what Jon has to say about it...

**Comment by JonMicheelsen** [comment] 2018-10-21 14:31
Nice find!
Probably one of those, where my compiler was "clever" enough to figure out what was intended and compiled without as much as a warning. We had a few of those.

**Comment by sol-oriens** [comment] 2018-10-29 20:59
I tested this on a rig that had the issue and it works indeed. I think I should add this fix to the Community Patch? (Initialized to 0, unless Jon says otherwise :))

**Comment by werman** [comment] 2018-10-30 10:49
Just my thoughts:
That calculation of atmoSteps had some strange intentions so 0 may not be a good value, I would advice to look at other variant where atmoSteps is initialized as 1, pick the best one and simplify this confusing branches.

**Comment by DaloLorn** [comment] 2018-10-30 18:18
Definitely - initializing to 0 results in multiplication *by* 0, which renders the whole operation moot.

**Comment by DaloLorn** [comment] 2020-05-22 07:43
@JonMicheelsen So what do you think your compiler defaulted to? Looking at the file again, I actually can't see any value that would be an *obvious* fit...

**Comment by DaloLorn** [comment] 2021-06-02 12:01
I actually fixed this in the MP: OpenSRProject/OpenStarRuler-Modpack@42399ba

Soooo closing now.

**Closed by DaloLorn** 2021-06-02 12:01 UTC
